UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Controllers/FunctionalityDevelopmentStepController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DataModel.Framework.DataAccess;
using Shared.WebCommon.UI.Web;
using DataModel.TaskTimeTracker.ApplicationDevelopment;
using DataModel.Framework.Configuration;
using Framework.Components.DataAccess;
using Framework.Components.UserPreference;

namespace ApplicationContainer.UI.Web.Areas.FunctionalityDevelopmentStep.Controllers
{
    public class FunctionalityDevelopmentStepController : Controller
    {
		string settingCategory = "FunctionalityDevelopmentStepIndexView";

		#region private methods

		private List<string> GetKendoColumnSetByFCMode(int fcModeId)
		{
			var lstColumns = new List<string>();

			var systemEntityTypeId = (int)Framework.Components.DataAccess.SystemEntity.FunctionalityDevelopmentStep;

			var dtConfigurations = FieldConfigurationUtility.GetFieldConfigurations(systemEntityTypeId, fcModeId, string.Empty);

			foreach (DataRow row in dtConfigurations.Rows)
			{
				var columnName = Convert.ToString(row[DataModel.Framework.Configuration.FieldConfigurationDataModel.DataColumns.Name]);
				//var title = Convert.ToString(row[DataModel.Framework.Configuration.FieldConfigurationDataModel.DataColumns.FieldConfigurationDisplayName]);
				//var width = Convert.ToString(row[DataModel.Framework.Configuration.FieldConfigurationDataModel.DataColumns.Width]);

				//str.AppendLine("        { field: '" + columnName + "', title: '" + title + "', width: " + width + " },");

				lstColumns.Add(columnName);
			}


			return lstColumns;
		}

		private string GetAllKendoColumns()
		{
			var str = new StringBuilder();

			str.AppendLine("    columns: [");
			str.AppendLine("        {");
			str.AppendLine("            title: \" \", field: 'FunctionalityDevelopmentStepId',");
			str.AppendLine("            filterable: false, sortable: false, width:30,");
			str.AppendLine("            headerTemplate: \"<input type='checkbox' id='checkAll'/>\",");
			str.AppendLine("            template: \"<input onclick='CheckWithHeader();' class='check-box' id='chkBox${FunctionalityDevelopmentStepId}' type='checkbox' value='${FunctionalityDevelopmentStepId}' /> \"");
			str.AppendLine("        },");
			str.AppendLine("        { field: \"Name\", title: \"Name\", width: 140, visible: false },");
			str.AppendLine("        { field: \"Description\", title: \"Description\", width: 190, visible: false },");
			str.AppendLine("        { field: \"SortOrder\", title: \"Sort Order\", width: 100, visible: false },");
			str.AppendLine("        { field: \"LastAction\", title: \"Last Action\", width: 140, visible: false },");
			str.AppendLine("        { field: \"UpdatedBy\", title: \"Updated By\", width: 140, visible: false },");
			str.AppendLine("        {");
			str.AppendLine("            field: \"UpdatedDate\", width: 140, visible: false, title: \"Updated Date\",");
			str.AppendLine("            format: \"{0:dd-MMM-yyyy}\",");
			str.AppendLine("            parseFormats: [\"yyyy-MM-dd'T'HH:mm:ss.zz\"],");
			str.AppendLine("            filterable: false");
			str.AppendLine("        },");
			str.AppendLine("        {");
			str.AppendLine("            field: \"DateCreated\", width: 140, visible: false, title: \"Date Created\",");
			str.AppendLine("            format: \"{0:dd-MMM-yyyy}\",");
			str.AppendLine("            parseFormats: [\"yyyy-MM-dd'T'HH:mm:ss.zz\"],");
			str.AppendLine("            filterable: false");
			str.AppendLine("        },");
			str.AppendLine("        {");
			str.AppendLine("            field: \"DateModified\", width: 140, visible: false, title: \"Date Modified\",");
			str.AppendLine("            format: \"{0:dd-MMM-yyyy}\",");
			str.AppendLine("            parseFormats: [\"yyyy-MM-dd'T'HH:mm:ss.zz\"],");
			str.AppendLine("            filterable: false");
			str.AppendLine("        },");

			// Add Button Columns
			str.AppendLine("        {");
			str.AppendLine("            title: \" \", width: 140, field: 'FunctionalityDevelopmentStepId',");
			str.AppendLine("            filterable: false,");
			str.AppendLine("            template: \"<a href='/FunctionalityDevelopmentStep/FunctionalityDevelopmentStep/Details/${FunctionalityDevelopmentStepId}'>Details</a>\"");
			str.AppendLine("        },");
			str.AppendLine("        {");
			str.AppendLine("            title: \" \", width: 140, field: 'FunctionalityDevelopmentStepId',");
			str.AppendLine("            filterable: false,");
			str.AppendLine("            template: \"<a href='/FunctionalityDevelopmentStep/FunctionalityDevelopmentStep/Edit/${FunctionalityDevelopmentStepId}'>Edit</a>\"");
			str.AppendLine("        },");
			str.AppendLine("        {");
			str.AppendLine("            title: \" \", width: 140, field: 'FunctionalityDevelopmentStepId',");
			str.AppendLine("            filterable: false,");
			str.AppendLine("            template: \"<a href='/FunctionalityDevelopmentStep/FunctionalityDevelopmentStep/Delete/${FunctionalityDevelopmentStepId}'>Delete</a>\"");
			str.AppendLine("        }");
			str.AppendLine("    ]");

			return str.ToString();
		}

		private string GetKendoGridConfiguration(string searchString, int fcModeId)
		{
			var str = new StringBuilder();

			str.AppendLine("");

			//str.AppendLine("$(\"#grid\").kendoGrid({");
			str.AppendLine("    " + GetAllKendoColumns() + ",");
			str.AppendLine("    dataSource: {");
			str.AppendLine("        transport: {");
			str.AppendLine("            read: \"/FunctionalityDevelopmentStep/FunctionalityDevelopmentStep/IndexResult?searchString=" + searchString + "\"");
			str.AppendLine("        },");
			str.AppendLine("        schema: {");
			str.AppendLine("            model: {");
			str.AppendLine("                    fields: {");
			str.AppendLine("                        FunctionalityDevelopmentStepId: { type: \"number\" },");
			str.AppendLine("                        Name: { type: \"string\" },");
			str.AppendLine("                        Description: { type: \"string\" },");
			str.AppendLine("                        SortOrder: { type: \"number\" },");
			str.AppendLine("                        LastAction: { type: \"string\" },");
			str.AppendLine("                        UpdatedBy: { type: \"string\" },");
			str.AppendLine("                        UpdatedDate: { type: \"date\" },");
			str.AppendLine("                        DateCreated: { type: \"date\" },");
			str.AppendLine("                        DateModified: { type: \"date\" }");
			str.AppendLine("                    }");
			str.AppendLine("            }");
			str.AppendLine("        },");
			str.AppendLine("        pageSize: 10");
			str.AppendLine("    },");
			str.AppendLine("    groupable: true,");
			str.AppendLine("    sortable: true,");
			//str.AppendLine("    filterable: true,");
			str.AppendLine("    pageable: {");
			str.AppendLine("        refresh: true,");
			str.AppendLine("        pageSizes: true,");
			str.AppendLine("        buttonCount: 5");
			str.AppendLine("    }");
			//str.AppendLine("});");

			return str.ToString();
		}

		#endregion

		#region Public Methods

		public FunctionalityDevelopmentStepDataModel GetById(int id)
		{
			var obj = new FunctionalityDevelopmentStepDataModel();
			obj.FunctionalityDevelopmentStepId = id;
			var list = TaskTimeTracker.Components.Module.ApplicationDevelopment.FunctionalityDevelopmentStepDataManager.GetEntityDetails(obj, SessionVariables.RequestProfile);
			if (list == null || list.Count == 0)
			{
				return null;
			}
			return list[0];
		}

		/// <summary>
		/// This method will be called by AJAX from Index Page for generating column set according to the passed fcModeId
		/// </summary>
		/// <param name="searchString"></param>
		/// <param name="page"></param>
		/// <param name="pageSize"></param>
		/// <returns></returns>
		public JsonResult ReloadKendoGridConfiguration(string fcModeId, string searchString)
		{
			PreferenceUtility.UpdateUserPreference(settingCategory, ApplicationCommon.FieldConfigurationMode, fcModeId.ToString());

			var configString = GetKendoColumnSetByFCMode(Convert.ToInt32(fcModeId));
			return Json(configString, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// This method will be called by AJAX from Index Page for generating Kendo Grid
		/// </summary>
		/// <param name="searchString"></param>
		/// <param name="page"></param>
		/// <param name="pageSize"></param>
		/// <returns></returns>
		[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
		public JsonResult IndexResult(string name, int? page, int? pageSize)
		{
			var obj = new FunctionalityDevelopmentStepDataModel();
			obj.Name = name;
			var list = TaskTimeTracker.Components.Module.ApplicationDevelopment.FunctionalityDevelopmentStepDataManager.GetEntitySearch(obj, SessionVariables.RequestProfile);
			return Json(list, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// Currently not in use, but this method can be called to retrieve the javascript code, will need further time to implement
		/// </summary>
		/// <param name="searchString"></param>
		/// <param name="page"></param>
		/// <param name="pageSize"></param>
		/// <returns></returns>
		public JavaScriptResult IndexGridConfiguration(string searchString, int? page, int? pageSize)
		{
			var str = new StringBuilder();

			str.AppendLine("$(\"#grid\").kendoGrid({");
			str.AppendLine("    columns: [");
			str.AppendLine("        { field: \"Name\", title: \"Name\", width: 140 },");
			str.AppendLine("        { field: \"Description\", title: \"Description\", width: 190 },");
			str.AppendLine("        {");
			str.AppendLine("            field: \"DateCreated\", title: \"Date Created\",");
			str.AppendLine("            format: \"{0:dd-MMM-yyyy}\",");
			str.AppendLine("            parseFormats: [\"yyyy-MM-dd'T'HH:mm:ss.zz\"],");
			str.AppendLine("            filterable: false");
			str.AppendLine("        },");
			str.AppendLine("        {");

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Controllers/HeaderController.cs
using Shared.WebCommon.UI.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationContainer.UI.Web.Areas.FunctionalityDevelopmentStep.Controllers
{
    public class HeaderController : Controller
    {
        //
        // GET: /FunctionalityDevelopmentStep/Header/
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult Header()
        {
            var applicationInfo = ApplicationCommon.ApplicationCache[SessionVariables.RequestProfile.ApplicationId];
            var applicationName = applicationInfo.Description;
            ViewBag.ApplicationName = applicationName;
            return PartialView();
        }

	}
}

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationContainer.UI.Web.Areas.FunctionalityDevelopmentStep.Controllers
{
	public class HomeController : Controller
	{
		//
		// GET: /FunctionalityDevelopmentStep/Home/

		public ActionResult Index()
		{
			return View();
		}

	}
}

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Views/FunctionalityDevelopmentStep/Create.cshtml
@model DataModel.TaskTimeTracker.ApplicationDevelopment.FunctionalityDevelopmentStepDataModel
@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm()) {
	@Html.ValidationSummary(true)

	<fieldset>
		<legend>FunctionalityDevelopmentStep</legend>

		<div class="editor-label">
			@Html.LabelFor(model => model.Name)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.Name)
			@Html.ValidationMessageFor(model => model.Name)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.Description)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.Description)
			@Html.ValidationMessageFor(model => model.Description)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.SortOrder)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.SortOrder)
			@Html.ValidationMessageFor(model => model.SortOrder)
		</div>

		<p>
			<input type="submit" value="Create" />
		</p>
	</fieldset>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Views/FunctionalityDevelopmentStep/Delete.cshtml
@model  List<DataModel.TaskTimeTracker.ApplicationDevelopment.FunctionalityDevelopmentStepDataModel>
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Functionality Development Step</legend>

        @Html.DisplayFor(Model => Model)

        <p>
            <input type="submit" value="Delete" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Views/FunctionalityDevelopmentStep/Details.cshtml
@model List<DataModel.TaskTimeTracker.ApplicationDevelopment.FunctionalityDevelopmentStepDataModel>
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Functionality Development Step</legend>

    @Html.DisplayFor(Model => Model)

</fieldset>

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = @Model.FunctionalityDevelopmentStepId }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Views/FunctionalityDevelopmentStep/Edit.cshtml
@model List<DataModel.TaskTimeTracker.ApplicationDevelopment.FunctionalityDevelopmentStepDataModel>
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Functionality Development Step</legend>
        @Html.EditorFor(Model => Model)
        <p>
            <input type="submit" value="Save" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UI/TaskTimeTracker/Web/Areas/FunctionalityDevelopmentStep/Views/FunctionalityDevelopmentStep/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script type="text/javascript" src="@Url.Content("/Areas/ReleaseNoteQualitative/Scripts/SearchFilterConfiguration.js")"></script>
<script type="text/javascript" src="@Url.Content("/Areas/ReleaseNoteQualitative/Scripts/CommonScripts.js")"></script>

<h2>Index</h2>

<div id="example" class="k-content">
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "FunctionalityDevelopmentStep", FormMethod.Get))
    {
        <p>
            <div id="searchFilterContainer">
            </div>

            @*<input id="txtNameFilter" type="text" />*@
            <br />
            <input id="btnFilter" type="button" value="Filter" />
        </p>
            
        <p>
            FC Mode: @Html.DropDownList("FieldConfigurationMode", null, new { id = "drpFCMode" })
            <br />
        </p>
    }
    <div id="grid" style="height: 380px"></div>
    <div>
        <input id="btnInsert" type="button" value="Insert" onclick="OnInsert();" />
        <input id="btnDelete" type="button" value="Delete" disabled="disabled" onclick="OnDelete();" />
        <input id="btnDetails" type="button" value="Details" disabled="disabled" onclick="OnDetails();" />
        <input id="btnUpdate" type="button" value="Update" disabled="disabled" onclick="OnUpdate();" />
        @*<input id="btnCommonUpdate" type="button" value="Common Update" />
        <input id="btnInlineUpdate" type="button" value="Inline Update" />*@
    </div>
</div>

<script>

    var entityName = "FunctionalityDevelopmentStep";
    var areaName = "FunctionalityDevelopmentStep";

    $(document).ready(function () {

        ConfigureSearchFilter($("#searchFilterContainer"));

        $("#grid").kendoGrid({
            @Html.Raw(@ViewBag.KendoUIConfigurationString)
        });

        var grid = $("#grid").data("kendoGrid");
        grid.bind("dataBound", MangeColumnVisibilityByFCMode);
        grid.dataSource.fetch();

        $('#drpFCMode').change(function () {
            MangeColumnVisibilityByFCMode();
        });

        $('#checkAll').click(function () {
            $("#grid .check-box").prop("checked", this.checked);
        });

        $('#btnFilter').click(function () {
            SubmitSearch();
        });

    });

</script>