Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcWebAPISample.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWebAPISample.Controllers
{
    public class ClientController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Insert()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

        public ActionResult Update(int id)
        {
            return View();
        }

    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using DataModel.TaskTimeTracker;
using TaskTimeTracker.Components.BusinessLayer;

namespace MvcWebAPISample.Controllers
{
    public class ClientsController : ApiController
    {

        // GET api/<controller>
        public IEnumerable<ClientDataModel> GetAllClients()
        {
            int auditId = 10;
            var data = new ClientDataModel();
            return ClientDataManager.GetEntityDetails(data, SessionVariables.RequestProfile, 0);
        }

        public ClientDataModel GetClient(int id)
        {
            int auditId = 10;
            var data = new ClientDataModel();
            data.ClientId = id;
            var results = ClientDataManager.GetEntityDetails(data, SessionVariables.RequestProfile, 0);
            if (results == null || results.Count == 0)
            {
                var resp = new HttpResponseMessage(HttpStatusCode.NotFound)
                 {
                     Content = new StringContent(string.Format("No Client with ID = {0}", id)),
                     ReasonPhrase = "Client ID Not Found"
                 };
                throw new HttpResponseException(resp);
            }
            return results[0];
        }

        public HttpResponseMessage PostClient(ClientDataModel data)
        {
            int auditId = 10;
            data.ClientId = null;
            data.ClientId = ClientDataManager.Create(data, SessionVariables.RequestProfile);

            var response = Request.CreateResponse<ClientDataModel>(HttpStatusCode.Created, data);
            response.Headers.Location = new Uri(Request.RequestUri, "/api/clients/" + data.ClientId.ToString());
            return response;
        }

        public void PutClient(int id, ClientDataModel data)
        {
            int auditId = 10;
            data.ClientId = id;
            ClientDataManager.UpdateSortOrderOnly(data, auditId);
        }

        public void DeleteClient(int id)
        {
            int auditId = 10;
            var data = new ClientDataModel();
            data.ClientId = id;
            ClientDataManager.Delete(data, SessionVariables.RequestProfile);
        }

    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/CustomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWebAPISample.Controllers
{
	public class CustomController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult MultiColumnComboBox(string SearchFor, string ControlId)
		{
			ViewBag.ProcId = SearchFor.Trim();
			ViewBag.ControlBlockId = "block" + ControlId.Trim();
			ViewBag.ControlId = ControlId.Trim();
			ViewBag.ControlTxtId = "txt" + ControlId.Trim();
			return View();
		}		

		public JsonResult LoadComboData(string strSearch, string SearchFor)
		{
			var clientNames = new List<string>();
			strSearch = strSearch.Trim();
			if (SearchFor.Trim() == "name")
			{
				var list = TaskTimeTracker.Components.BusinessLayer.ClientDataManager.GetList(SessionVariables.RequestProfile);

				foreach(var item in list)
				{
					clientNames.Add(item.Name);
				}
			}
			return Json(clientNames, JsonRequestBehavior.AllowGet);
		}
 
 
	}
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcWebAPISample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using MvcWebAPISample.Models;

namespace MvcWebAPISample.Controllers
{
    public class ProductsController : ApiController
    {
        Product[] products = new Product[] 
        { 
            new Product { Id = 1, Name = "Tomato Soup", Category = "Groceries", Price = 1 }, 
            new Product { Id = 2, Name = "Yo-yo", Category = "Toys", Price = 3.75M }, 
            new Product { Id = 3, Name = "Hammer", Category = "Hardware", Price = 16.99M } 
        };

        public IEnumerable<Product> GetAllProducts()
        {
            return products;
        }

        public Product GetProductById(int id)
        {
            var product = products.FirstOrDefault((p) => p.Id == id);
            if (product == null)
            {
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));
            }
            return product;
        }
    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/UserLoginsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Framework.Components.DataAccess;

namespace MvcWebAPISample.Controllers
{
    public class UserLoginsController : ApiController
    {

        // GET api/<controller>
        public IEnumerable<Framework.Components.LogAndTrace.UserLoginHistoryDataModel> Get(string userId)
        {
            var auditId = 0;
            if (!string.IsNullOrEmpty(userId))
            {
                auditId = Convert.ToInt32(userId);
            }

			var requestProfile = new RequestProfile();
			requestProfile.AuditId = auditId;
			requestProfile.ApplicationId = Convert.ToInt32(ConfigurationManager.AppSettings["StartupApplicationId"]);

            var data = new Framework.Components.LogAndTrace.UserLoginHistoryDataModel();
            data.UserId = auditId;
			var list = Framework.Components.LogAndTrace.UserLoginHistoryDataManager.GetLastUrls(data, 7, requestProfile);
            return list;
        }

    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MvcWebAPISample.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post(string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Database/Framework.Reporting/Task Time Tracker/MvcWebAPISample/MvcWebAPISample/Views/AutoComplete/AutoCompleteSample.cshtml
@{
    ViewBag.Title = "AutoCompleteSample";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AutoCompleteSample</h2>

<h4>
    Render Custom action to generate Multiple column Combo.</h4>
<table>
    <tr>
        <td>
            Names:
        </td>
        <td>
            @{Html.RenderAction("MultiColumnComboBox", "Custom", new { ControlFor = "name", ControlId = "comboName" });}
        </td>
    </tr>
    
</table>

@{
    Layout = null;
}
<style type="text/css">
    table td
    {
        padding: 3px 5px;
        margin: 0;
    }
    a:link
    {
        text-decoration: none;
        cursor: pointer;
    }
    .tdHeader
    {
        background-color: #CEF6F5;
    }
    .DataBlock
    {
        max-width: 520px;
        min-width: 215px;
        max-height: 200px;
        overflow: auto;
        background-color: #fff;
    }
    .renderpart
    {
        z-index: 99999;
        position: absolute;
    }
</style>
<input type="hidden" id="@ViewBag.ProcId" name="@ViewBag.ProcId" value=""/>
<input type="hidden" id="@ViewBag.ControlId" name="@ViewBag.ControlId" value=""/>
<input type="text" name="@ViewBag.ControlTxtId" id="@ViewBag.ControlTxtId" autocomplete="off"/>
<div class="@ViewBag.ControlTxtId renderpart">
    <div class="DataBlock">
        <div id="@ViewBag.ControlBlockId" style="max-width: 520px;">
        </div>
    </div>
</div>
<script src="../../Scripts/jquery-1.7.1.js" type="text/javascript"></script>
<script src="../../Scripts/json.debug.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".renderpart").hide();
        var txtid = "#" + '@ViewBag.ControlTxtId';
        var renderpart = "." + '@ViewBag.ControlTxtId';
        var selectlinkvalueid = ".Get" + '@ViewBag.ProcId';

        $(selectlinkvalueid).live("click", function () {
            var value = $(this).attr('id');
            var valueText = $(this).attr('title');
            $("#@ViewBag.ControlId").val(value);
            $(txtid).val(valueText);
            $(renderpart).slideUp("slow");
        });
 
        $(txtid).keyup(function () {
            var value = $(txtid).val();
            var Procvalue = '@ViewBag.ProcId';
            var controlid = "#" + '@ViewBag.ControlBlockId';

            value = encodeURI(value);
            if (value.length > 2) {
                $.ajaxSetup({ cache: false });
                $.getJSON("/Custom/LoadComboData", { strSearch: " " + value, ProcId: " " + Procvalue }, function (data) {
                    $(controlid).html("");
                    var activecols = $("#hdnActiveColumns").val();
                    var htmlrow = "";
                    var tempprocId = '@ViewBag.ProcId';
                    var jsondata = JSON.stringify(data);
                    $(controlid).html(CreateDynamicTable(jsondata, tempprocId));
                    $(renderpart).slideDown("slow");
                });
                $.ajaxSetup({ cache: true });
            }
            else {
                $(renderpart).slideUp("slow");
            }
        });
        $(txtid).focusin(function () {
            var txtid = "#" + '@ViewBag.ControlTxtId';
            var value = $(txtid).val();
            var Procvalue = '@ViewBag.ProcId';
            var controlid = "#" + '@ViewBag.ControlBlockId';
            value = encodeURI(value);
            if (value.length > 2) {
                $.ajaxSetup({ cache: false });
                $.getJSON("/Custom/LoadComboData", { strSearch: " " + value, ProcId: " " + Procvalue }, function (data) {
                    $(controlid).html("");
                    var htmlrow = "";
                    var tempprocId = '@ViewBag.ProcId';
                    var jsondata = JSON.stringify(data);
                    $(controlid).html(CreateDynamicTable(jsondata, tempprocId));
                    $(renderpart).slideDown("slow");
                });
                $.ajaxSetup({ cache: true });
            }
            else {
                $(renderpart).slideUp("slow");
            }
        });
        function CreateDynamicTable(objArray, tempprocId) {
            var array = JSON.parse(objArray);
            var str = '<table style="width:100%;">';
            str += '<tr>';
            for (var index in array[0]) {
                str += '<th scope="col">' + index + '</th>';
            }
            str += '</tr>';
            str += '<tbody>';
            var flag = false;
            var ids;
            for (var i = 0; i < array.length; i++) {
                str += (i % 2 == 0) ? '<tr>' : '<tr>';
                for (var index in array[i]) {
                    if (flag == false) {
                        ids = array[i][index];
                        flag = true;
                    }
                    str += '<td><a id="' + ids + '" class="Get' + tempprocId + '" title="' + array[i][index] + '" href="#">' + array[i][index] + '</a></td>';
                }
                str += '</tr>';
            }
            str += '</tbody>';
            str += '</table>';
            return str;
        }
    });
    $(document).click(function (evt) {
        var renderpart = "." + '@ViewBag.ControlTxtId';
        var theElem = (evt.srcElement) ? evt.srcElement : evt.target;
 
        if (theElem.id == "main" || theElem.id == "sub1") {
            $(renderpart).slideUp("fast");
        }
    });
</script>

 